default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: cinema_development

test:
  <<: *default
  database: cinema_test

production:
  <<: *default
  database: cinema_production
